version: '3.9'

services:
  main-app:
    container_name: main-app
    image: nest-with-skywalking-app:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - '3000:3000'
      - '9229:9229'
    networks:
      - app-network
    volumes:
      - .:/usr/src/
    restart: unless-stopped
    healthcheck:
      test:     
        ["CMD-SHELL", "curl --silent --fail -X GET http://localhost:3000 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s
    depends_on:
      skywalking-logger:
        condition: service_healthy
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    env_file: .env
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.http.ssl.enabled=false
      - xpack.security.enabled=true
      - discovery.type=single-node
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - app-network
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test:     
        ["CMD-SHELL", "curl --silent --fail --user elastic:${ELASTIC_PASSWORD} -X GET http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=50s || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s
  skywalking-logger:
    container_name: skywalking_logger
    image: apache/skywalking-oap-server:9.7.0
    restart: always
    environment:
      - SW_CORE_REST_HOST=0.0.0.0
      - SW_CORE_GRPC_HOST=0.0.0.0
      - SW_HEALTH_CHECKER=default
      - SW_HEALTH_CHECKER_INTERVAL_SECONDS=10
      - SW_STORAGE=elasticsearch
      - SW_ES_USER=elastic
      - SW_ES_PASSWORD=myElasticPassword
      - SW_STORAGE_ES_CLUSTER_NODES=elasticsearch:9200
      - SW_STORAGE_ES_HTTP_PROTOCOL=http
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network
    ports:
      - 11800:11800
      - 12800:12800
      - 9412:9412
    depends_on:
      elasticsearch: 
        condition: service_healthy
  skywalking-ui:
    container_name: skywalking_ui
    image: apache/skywalking-ui
    restart: always
    environment:
      - SW_OAP_ADDRESS=http://skywalking-logger:12800
      - SW_ZIPKIN_ADDRESS=http://skywalking-logger:9412
      - SW_CORE_METRICS_DATA_TTL=7
      - SW_CORE_RECORD_DATA_TTL=3
    networks:
      - app-network
    ports:
      - 18080:8080
    depends_on:
      skywalking-logger:
        condition: service_healthy
   
networks:
  app-network:

volumes:
  postgres-data:
  esdata:
  